# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e46d964002eebddeb912b8c2c0f1827751bc798ede1adb1c1811ef6b8396506ec30cc43b7cdc6d42ee6d28ec752a4d95094661b4ca377a756811b8f9822d284

test:
  secret_key_base: aa5cf15968fc9dce482ab8aac4eed0fa06d2a635c14b41e9cf394a79d61032bd63944db0c103ecef238a0de47623c12ea3e16bf125fd4a0e921ffe406b2e02d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
